In [4]:
#NUMPY
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr}")

1D Array: [1 2 3 4 5]


In [6]:
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.dtype)

[1 2 3 4]
int64


In [7]:
a=np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [9]:
b=np.ones((4,4),dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
#CLEANING USING RANGE
marks=np.array([85,78,-5,120,98,45])
valid_marks=np.arange(0,101)
final_marks=np.where(np.isin(marks,valid_marks),marks,np.nan)
print(final_marks)

[85. 78. nan nan 98. 45.]


In [11]:
#MASKING(advanced slicing)
age=np.array([32,-5,101,10,2,-20])
cleaned_age=np.where(age<0,'NOT VALID',age)
print(cleaned_age)

['32' 'NOT VALID' '101' '10' '2' 'NOT VALID']


In [12]:
data=np.array([10,20,30,40,50,np.nan,70])
indices=np.arange(len(data))
valid_indices=indices[~np.isnan(data)] #[f,f,f,f,f,t,f]->after applying (~)->[t,t,t,t,t,f,t]

# masking(works with boolean only)
cleaned_data=data[valid_indices] # data[t,t,t,t,t,f,t] ->whatever is true it gives in print

print(cleaned_data)

[10. 20. 30. 40. 50. 70.]


In [13]:
data=np.array([10,20,30,40,50,np.nan,70])
mask=data==-1
print(mask)

[False False False False False False False]


In [14]:
data=np.array([1,2,3,4])
mask=data==-1
print(mask)
data1=data[mask]
print(data1)

[False False False False]
[]


In [15]:
data_email=np.array([-1,-1,20])
indices=np.arange(len(data_email))
mask=data_email!=-1
print(mask)

cleaned_data=data_email[mask]

print(cleaned_data)

[False False  True]
[20]


In [16]:
data=np.array([1,2,-1,-1,20],dtype=float)
data[data==-1]=np.nan
print(data)

[ 1.  2. nan nan 20.]


In [18]:
data_email=np.array([-1,-1,20],dtype=float)
data_email[data_email==-1]=np.nan
print(data_email)

[nan nan 20.]


In [19]:
#LINSPACE
# gives gap btwn all data
l1,r=np.linspace(1,5,retstep=True)
print(r)

0.08163265306122448


In [20]:
#start,stop,step
l1=np.linspace(1,5,5)
print(l1)

[1. 2. 3. 4. 5.]


In [21]:
# Time-series Cleaning(Missing Timestamp)
# we dont have enough points and we need more data 

time=np.array([0,1,3,6])
clean_time=np.linspace(time[0],time[-1],7) #time[0]-> start i.e. 0 and [-1]->end i.e. 6

print(clean_time)

[0. 1. 2. 3. 4. 5. 6.]


In [22]:
dataa=np.array([1,2,3,4])

#checking form of array [1d,2d etc]
print(data.ndim)

1


In [23]:
dataa=np.reshape(dataa,(2,2))
print(dataa)
data2=np.reshape(dataa,(2,-1)) # -1 means give any col size
print(data2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [24]:
#MATHEMATICAL OPERATOR
a=np.arange(5)
# b=np.arange(6) #error as size not same 
b=np.arange(5)
sum1=a+b
print(sum1)

c=np.subtract(a,b)
print(c)


[0 2 4 6 8]
[0 0 0 0 0]


In [25]:
d=np.concatenate((a,b),axis=0)
print(d)

[0 1 2 3 4 0 1 2 3 4]


In [28]:
e=np.divide(a,b)
print(e)

[nan  1.  1.  1.  1.]


C:\Users\acer\AppData\Local\Temp\ipykernel_28644\679676541.py:1: RuntimeWarning: invalid value encountered in divide
  e=np.divide(a,b)


In [29]:
mode=np.mod(a,b)
print(mode)

[0 0 0 0 0]


C:\Users\acer\AppData\Local\Temp\ipykernel_28644\2415000746.py:1: RuntimeWarning: divide by zero encountered in remainder
  mode=np.mod(a,b)


In [31]:
x=np.array([1,2,3,4])

y=np.exp(x)
print(y)

s=a%b
print(s)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0 0 0 0 0]


C:\Users\acer\AppData\Local\Temp\ipykernel_28644\1647651556.py:6: RuntimeWarning: divide by zero encountered in remainder
  s=a%b


In [32]:
np.log(x)
np.log2(x)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [35]:
print(np.mean(dataa))

2.5


In [34]:
print(np.max(dataa))

4


In [36]:
a=np.array([1,2,3,4])

print (np.equal(data,2)) # can be used in mask


[False  True False False False]


In [37]:
print(a.reshape(2,2))


[[1 2]
 [3 4]]


In [38]:
d=np.arange(10).reshape((2,-1))
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
d[0][1]
d[0]

array([0, 1, 2, 3, 4])

In [40]:
# a[start_row : end_row, start_col:end_col ]

d1=d[:,0]
print(d1)

d2=[0,1]
print(d2)

[0 5]
[0, 1]


In [41]:
d3=d[:,0]
print(type(d3))


<class 'numpy.ndarray'>


In [42]:
d3=d[:,0:]
print(type(d3))
print(d3)

<class 'numpy.ndarray'>
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [43]:
marks=np.array([85,78,92,73,65])
passed=marks[marks>=80]

print(passed)

[85 92]


In [44]:
students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 30]
])

id=students[:,:1]
print (id)

[[101]
 [102]
 [103]
 [104]]


In [45]:
mask = students[:, 1] <= 80
print(mask)
failed_students = students[mask]

failed_ids = failed_students[:, 0]

print(failed_students)
print(failed_ids)


[False  True False  True]
[[102  45]
 [104  30]]
[102 104]


In [47]:
students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 30]
])

id=students[:,:1]
print (id) 

[[101]
 [102]
 [103]
 [104]]


In [48]:
fail=students[students<=80]
print(fail) 

[45 30]


In [49]:
import numpy as np

students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 30]
])

failed_students = students[students[:, 1] <= 80]
print(failed_students)


[[102  45]
 [104  30]]


In [50]:
#Ravel-> converting 2d into 1d

b=np.ravel(a)
print(b)

[1 2 3 4]


In [51]:
c=np.transpose(a)
print(c)

[1 2 3 4]


In [52]:
#RANDOM
import random as rd 
x=rd.random()
print(x)

0.48517540092414246


In [53]:
y = np.random.random((2, 3))
print(y)
z=np.random.randint(2,10)
print(z)

[[0.72147821 0.92106719 0.11904788]
 [0.59524918 0.83995724 0.13327253]]
3


In [54]:
z=np.random.randint(2,10,2,dtype=np.uint32)
print(z)

[6 7]


In [55]:
ap=np.array([1,2,3,4])
z=np.random.choice(a)
print(z)


2


In [56]:
#STRING OPERATOR
a=np.array(["Numpy Clarss"," need World"])
b=np.array(["need feedback"])
c=np.char.add(a,b)
print (c)
d=np.char.multiply(a,2)
print(d)
v=np.char.capitalize(b)
print(v)
t=np.char.title(a)
print(t)
s=np.array(['i m shreya kaushal'])
h=np.char.upper(s)
print(h)
f=np.char.lower(s)
print(f)

['Numpy Clarssneed feedback' ' need Worldneed feedback']
['Numpy ClarssNumpy Clarss' ' need World need World']
['Need feedback']
['Numpy Clarss' ' Need World']
['I M SHREYA KAUSHAL']
['i m shreya kaushal']


In [57]:
d=np.char.center(a,50,fillchar="*")
print(d)

['*******************Numpy Clarss*******************'
 '******************* need World********************']


In [58]:
j=np.char.join(['--','*'],a)
print(j)
k=np.char.join(['--'],a)
print(k)

['N--u--m--p--y-- --C--l--a--r--s--s' ' *n*e*e*d* *W*o*r*l*d']
['N--u--m--p--y-- --C--l--a--r--s--s' ' --n--e--e--d-- --W--o--r--l--d']


In [59]:
r=np.char.replace(b,'need feedback','Uknown')
print(r)
s=np.char.split(a)
print(s)
print(type(s))

['Uknown']
[list(['Numpy', 'Clarss']) list(['need', 'World'])]
<class 'numpy.ndarray'>


In [70]:
# how to know that when we print s what would be the datatype of the output
c=type(s[1])
print(c)




<class 'list'>


In [71]:

a=np.arange(5)
b=np.linspace(5,10,5,dtype=int)

print(a,b)
np.hstack((a,b))
np.vstack((a,b))
np.hstack((a,b)).T

[0 1 2 3 4] [ 5  6  7  8 10]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [72]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 10]])

In [73]:
import pandas as pd
import numpy as np

In [76]:
df=pd.read_csv("data_cleaning_method2.csv")

In [77]:
df.head()

,roll,name,marks,branch
0,101,Anuj,85,CSE
1,102,NaN,78,ECE
2,103,Ravi,Ninety,ME
3,104,Priya,105,CSE
4,105,Aman,-10,CSE


In [78]:
headers=df.columns.to_numpy()
print(headers)

['roll' 'name' 'marks' 'branch']


In [79]:
data=df.to_numpy()
print(data)

[[101 'Anuj' '85' 'CSE']
 [102 nan '78' 'ECE']
 [103 'Ravi' 'Ninety' 'ME']
 [104 'Priya' '105' 'CSE']
 [105 'Aman' '-10' 'CSE']
 [106 'Neha' '88' nan]]


In [82]:
name=data[:,1]
print(name) 

['Anuj' nan 'Ravi' 'Priya' 'Aman' 'Neha']


In [85]:
mask=(name==np.nan)
print(mask)

[False False False False False False]


In [110]:
valid=name[mask]
print(valid)


[]


In [106]:

for i in range(len(name)):
   if type(name[i])==float:
     name[i]="unknown"
       
       
    

In [107]:
print(name)

['Anuj' 'unknown' 'Ravi' 'Priya' 'Aman' 'Neha']


In [111]:
name=data[:,2]
print(name)

['85' '78' 'Ninety' '105' '-10' '88']


In [115]:
mask1=name=='Ninety'
name[mask1]=90
print(mask1)

90


In [117]:
mask2=name=='-10'
name[mask2]=np.nan
print(mask2)

10


In [118]:
mask3=name=='-105'
name[mask3]=100
print(name)

['85' '78' 'Ninety' '105' '-10' '88']


In [120]:
mask1=name=='Ninety'
name[mask1]=90
mask2=name=='-10'
name[mask2]=np.nan
mask3=name=='-105'
name[mask3]=100
print(name)

['85' '78' 90 '105' nan '88']


In [123]:
name=data[:,3]
print(name)


['CSE' 'ECE' 'ME' 'CSE' 'CSE' nan]


In [124]:
for i in range(len(name)):
   if type(name[i])==float:
     name[i]="CSE"

In [125]:
print(name)

['CSE' 'ECE' 'ME' 'CSE' 'CSE' 'CSE']


In [126]:
print(data)

[[101 'Anuj' '85' 'CSE']
 [102 'unknown' '78' 'ECE']
 [103 'Ravi' 90 'ME']
 [104 'Priya' '105' 'CSE']
 [105 'Aman' 'unknown' 'CSE']
 [106 'Neha' '88' 'CSE']]


In [2]:
import pandas as pd  # type: ignore
import numpy as np
df= pd.read_csv("students_dataset.txt")
print(df)

  Student Department  Year  Marks
0    Anuj        CSE     1     85
1    Ravi        ECE     2     78
2   Priya        CSE     1     92
3    Aman         ME     3     66
4    Neha        ECE     2     74
5   Rahul        CSE     1     88
6   Pooja         ME     3     70
7   Karan        CSE     2     90
8   Sneha        ECE     1     81
9   Vikas         ME     3     69


In [3]:
df1=df.groupby('Department')

In [4]:
print(df1)

In [6]:
for key,value in df1:
    print(key)
    print(value)

CSE
  Student Department  Year  Marks
0    Anuj        CSE     1     85
2   Priya        CSE     1     92
5   Rahul        CSE     1     88
7   Karan        CSE     2     90
ECE
  Student Department  Year  Marks
1    Ravi        ECE     2     78
4    Neha        ECE     2     74
8   Sneha        ECE     1     81
ME
  Student Department  Year  Marks
3    Aman         ME     3     66
6   Pooja         ME     3     70
9   Vikas         ME     3     69


In [7]:
d=dict(list(df1))
print(d)

{'CSE':   Student Department  Year  Marks
0    Anuj        CSE     1     85
2   Priya        CSE     1     92
5   Rahul        CSE     1     88
7   Karan        CSE     2     90, 'ECE':   Student Department  Year  Marks
1    Ravi        ECE     2     78
4    Neha        ECE     2     74
8   Sneha        ECE     1     81, 'ME':   Student Department  Year  Marks
3    Aman         ME     3     66
6   Pooja         ME     3     70
9   Vikas         ME     3     69}


In [9]:
df1=pd.read_csv('df1.txt')
df2=pd.read_csv('df2.txt')
display(df1,df2)

,StudentID,Name,Department,Marks
0,101,Anuj,CSE,85
1,102,Ravi,ECE,78
2,103,Priya,CSE,92
3,104,Aman,ME,66
4,105,Neha,ECE,74


,StudentID,Name,Department,Marks
0,106,Rahul,CSE,88
1,107,Pooja,ME,70
2,108,Karan,CSE,90
3,109,Sneha,ECE,81
4,110,Vikas,ME,69


In [10]:
d = pd.concat([df1, df2], axis=1)
print(d)

   StudentID   Name Department  Marks  StudentID   Name Department  Marks
0        101   Anuj        CSE     85        106  Rahul        CSE     88
1        102   Ravi        ECE     78        107  Pooja         ME     70
2        103  Priya        CSE     92        108  Karan        CSE     90
3        104   Aman         ME     66        109  Sneha        ECE     81
4        105   Neha        ECE     74        110  Vikas         ME     69


In [12]:
pd.merge(df1,df2,how='left')

,StudentID,Name,Department,Marks
0,101,Anuj,CSE,85
1,102,Ravi,ECE,78
2,103,Priya,CSE,92
3,104,Aman,ME,66
4,105,Neha,ECE,74


In [13]:
pd.merge(df1,df2,how='outer')

,StudentID,Name,Department,Marks
0,101,Anuj,CSE,85
1,102,Ravi,ECE,78
2,103,Priya,CSE,92
3,104,Aman,ME,66
4,105,Neha,ECE,74
5,106,Rahul,CSE,88
6,107,Pooja,ME,70
7,108,Karan,CSE,90
8,109,Sneha,ECE,81
9,110,Vikas,ME,69


In [14]:
pd.merge(df1,df2,how='inner')

,StudentID,Name,Department,Marks


In [15]:
pd.merge(df1,df2,how='outer',on='StudentID')

,StudentID,Name_x,Department_x,Marks_x,Name_y,Department_y,Marks_y
0,101,Anuj,CSE,85.0,NaN,NaN,NaN
1,102,Ravi,ECE,78.0,NaN,NaN,NaN
2,103,Priya,CSE,92.0,NaN,NaN,NaN
3,104,Aman,ME,66.0,NaN,NaN,NaN
4,105,Neha,ECE,74.0,NaN,NaN,NaN
5,106,NaN,NaN,NaN,Rahul,CSE,88.0
6,107,NaN,NaN,NaN,Pooja,ME,70.0
7,108,NaN,NaN,NaN,Karan,CSE,90.0
8,109,NaN,NaN,NaN,Sneha,ECE,81.0
9,110,NaN,NaN,NaN,Vikas,ME,69.0


In [18]:
df1.join(df2,lsuffix='1',rsuffix ='2',how='inner')

,StudentID1,Name1,Department1,Marks1,StudentID2,Name2,Department2,Marks2
0,101,Anuj,CSE,85,106,Rahul,CSE,88
1,102,Ravi,ECE,78,107,Pooja,ME,70
2,103,Priya,CSE,92,108,Karan,CSE,90
3,104,Aman,ME,66,109,Sneha,ECE,81
4,105,Neha,ECE,74,110,Vikas,ME,69


In [20]:
df2=df2.set_index(pd.Index(['a','b','c',3,4]))

In [21]:
df2

,StudentID,Name,Department,Marks
a,106,Rahul,CSE,88
b,107,Pooja,ME,70
c,108,Karan,CSE,90
3,109,Sneha,ECE,81
4,110,Vikas,ME,69


In [22]:
df1.join(df2,lsuffix='1',rsuffix ='2',how='inner')

,StudentID1,Name1,Department1,Marks1,StudentID2,Name2,Department2,Marks2
3,104,Aman,ME,66,109,Sneha,ECE,81
4,105,Neha,ECE,74,110,Vikas,ME,69


In [23]:
df1

,StudentID,Name,Department,Marks
0,101,Anuj,CSE,85
1,102,Ravi,ECE,78
2,103,Priya,CSE,92
3,104,Aman,ME,66
4,105,Neha,ECE,74


In [24]:
df=pd.read_csv('students_dirty_data2.csv')

In [25]:
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101.0,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102.0,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103.0,NaN,-10,ME,NaN,2023/03/15
3,104.0,NaN,105,NaN,priya@gmail.com,invalid
4,105.0,Priya,NaN,NaN,,NaN
5,105.0,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,NaN,123,45,cse,invalid,2023-13-01


In [27]:
df['Roll'].interpolate(inplace=True)

In [28]:
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101.0,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102.0,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103.0,NaN,-10,ME,NaN,2023/03/15
3,104.0,NaN,105,NaN,priya@gmail.com,invalid
4,105.0,Priya,NaN,NaN,,NaN
5,105.0,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,105.0,123,45,cse,invalid,2023-13-01


In [29]:
df['Roll']=pd.to_numeric(df['Roll'],downcast='integer')
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103,NaN,-10,ME,NaN,2023/03/15
3,104,NaN,105,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,105,123,45,cse,invalid,2023-13-01


In [33]:
df['Name']=df['Name'].str.strip()
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103,NaN,-10,ME,NaN,2023/03/15
3,104,NaN,105,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,105,123,45,cse,invalid,2023-13-01


In [37]:
df['Name'].fillna('Unknown', inplace = True)
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103,Unknown,-10,ME,NaN,2023/03/15
3,104,Unknown,105,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,105,123,45,cse,invalid,2023-13-01


In [40]:
df['Name'].replace('123','unknown', inplace = True)
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,Ninety,ECE,ravi@gmail,2023-11-10
2,103,Unknown,-10,ME,NaN,2023/03/15
3,104,Unknown,105,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45,cse,invalid,2023-13-01


In [41]:
pd.to_numeric(df['Marks'],downcast='integer',errors='coerce')

0     85.0
1      NaN
2    -10.0
3    105.0
4      NaN
5     88.0
6     45.0
Name: Marks, dtype: float64

In [42]:
df['Marks']=pd.to_numeric(df['Marks'],downcast='integer',errors='coerce')
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,NaN,ECE,ravi@gmail,2023-11-10
2,103,Unknown,-10.0,ME,NaN,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [43]:
df['Marks'].mean()
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,NaN,ECE,ravi@gmail,2023-11-10
2,103,Unknown,-10.0,ME,NaN,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,NaN,NaN,,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [44]:
df['Marks'].fillna(df['Marks'].mean())

0     85.0
1     62.6
2    -10.0
3    105.0
4     62.6
5     88.0
6     45.0
Name: Marks, dtype: float64

In [46]:
df['Marks'].fillna(df['Marks'].mean(),inplace=True)
df

C:\Users\acer\AppData\Local\Temp\ipykernel_11476\1344588634.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].mean(),inplace=True)


,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,62.6,ECE,ravi@gmail,2023-11-10
2,103,Unknown,-10.0,ME,NaN,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,62.6,NaN,,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [48]:
df.loc[df['Marks']<0 | (df['Marks']>100),'Marks']=0
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,62.6,ECE,ravi@gmail,2023-11-10
2,103,Unknown,0.0,ME,NaN,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,62.6,NaN,,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [51]:
df.loc[df['Marks']==0.0,'Marks']=df['Marks'].mean
df


C:\Users\acer\AppData\Local\Temp\ipykernel_11476\3827609299.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0     85.000000
1     62.600000
2     64.028571
3    105.000000
4     62.600000
5     88.000000
6     45.000000
Name: Marks, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['Marks']==0.0,'Marks']=df['Marks'].mean


,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,62.6,ECE,ravi@gmail,2023-11-10
2,103,Unknown,64.028571,ME,NaN,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,62.6,NaN,,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [54]:
p='^[\w]+@[\w]+\.[\w]+$'
df['Email']=df['Email'].where(df['Email'].str.match(p),'invalid')

In [55]:
df

,Roll,Name,Marks,Branch,Email,Join_Date
0,101,Anuj,85.0,CSE,anuj@gmail.com,2023-01-10
1,102,Ravi,62.6,ECE,invalid,2023-11-10
2,103,Unknown,64.028571,ME,invalid,2023/03/15
3,104,Unknown,105.0,NaN,priya@gmail.com,invalid
4,105,Priya,62.6,NaN,invalid,NaN
5,105,Priya,88.0,CSE,anuj@gmail.com,2024-09-30
6,105,Priya,45.0,cse,invalid,2023-13-01


In [57]:
date1=pd.to_datetime(df['Join_Date'],errors='coerce')

In [58]:
date1

0   2023-01-10
1   2023-11-10
2          NaT
3          NaT
4          NaT
5   2024-09-30
6          NaT
Name: Join_Date, dtype: datetime64[ns]

In [74]:
date2 = pd.to_datetime(df['Join_Date'], format='%Y-%d-%m', errors='coerce')


In [75]:
date2

0   2023-10-01
1   2023-10-11
2          NaT
3          NaT
4          NaT
5          NaT
6   2023-01-13
Name: Join_Date, dtype: datetime64[ns]

In [76]:
date3 = pd.to_datetime(df['Join_Date'], format='%Y-%d-%m', errors='coerce')
date3

0   2023-10-01
1   2023-10-11
2          NaT
3          NaT
4          NaT
5          NaT
6   2023-01-13
Name: Join_Date, dtype: datetime64[ns]

In [77]:
date1.fillna(date2)

0   2023-01-10
1   2023-11-10
2          NaT
3          NaT
4          NaT
5   2024-09-30
6   2023-01-13
Name: Join_Date, dtype: datetime64[ns]

In [78]:
d4=date1.fillna(date2)
d4

0   2023-01-10
1   2023-11-10
2          NaT
3          NaT
4          NaT
5   2024-09-30
6   2023-01-13
Name: Join_Date, dtype: datetime64[ns]

In [79]:
d4.fillna(date3)
d4

0   2023-01-10
1   2023-11-10
2          NaT
3          NaT
4          NaT
5   2024-09-30
6   2023-01-13
Name: Join_Date, dtype: datetime64[ns]