In [2]:
import numpy as np
a=np.array((1,2,3))
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
print(a.ndim)

1


In [5]:
b=np.array(([1,2,3],[1,2,3]))
print(b)

[[1 2 3]
 [1 2 3]]


In [6]:
# CHECKING OF DIMENSIONS
print(b.ndim)

2


In [7]:
n = np.zeros((2,3))

In [8]:
print(n)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
a=np.array([1,2,3])
print(a.dtype)

int64


In [4]:
b=np.array(['1','2','3','4','5'])
print(b)
print(b.dtype)

['1' '2' '3' '4' '5']
<U1


In [6]:
#CONVERSION
c=b.astype('i')
print(c)
print(c.dtype)

[1 2 3 4 5]
int32


In [8]:
#INDEXING
b=np.array(['1','2','3','4','5'])
print(b[0])
print(b[1])
print(b[-1])

1
2
5


In [10]:
#ACCESSING ELEMENTS OF 1 DIMENSIONSAL ARRAY 
b=np.array(([1,2,3],[1,2,3]))
print(b)
print(b[0,0])
print(b[0,1])
print(b[0,2])

[[1 2 3]
 [1 2 3]]
1
2
3


In [11]:
#ACCESSING ELEMENTS OF 2 DIMENSIONSAL ARRAY 
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b[1,0])
print(b[1,1])
print(b[1,2])

[[1 2 3]
 [4 5 6]]
4
5
6


In [15]:
#SLICING
s=np.array([23,50,60,90,100,12,233,234,111,389,567])
print(s[0:2])
print(s[3:])
print(s[:5])
print(s[0:10:2])#2 means it give output of 1 gap elements

[23 50]
[ 90 100  12 233 234 111 389 567]
[ 23  50  60  90 100]
[ 23  60 100 233 111]


In [21]:
#2D slicing
s=np.array([[23,50,60,90,100,20],
            [12,233,234,111,389,567]])
print(s[0,0:5])
print(s[1,0:5])
print(s[0:5,2:5]) #it decides which rows and columns to select for the output

[ 23  50  60  90 100]
[ 12 233 234 111 389]
[[ 60  90 100]
 [234 111 389]]


In [22]:
a=np.array([1,2,3,4,5])
print(a.ndim)
print(a.shape)

1
(5,)


In [23]:
s=np.array([[23,50,60,90,100,20],
            [12,233,234,111,389,567]])
print(s.shape)

(2, 6)


In [27]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [29]:
#ITERATE ONE DIMENSIONAL ARRAY IN NUMPY
a=np.array([1,2,3,4,5,6])
print("Iterating")
for n in a:
    print(n)
    print(type(a))

Iterating
1
<class 'numpy.ndarray'>
2
<class 'numpy.ndarray'>
3
<class 'numpy.ndarray'>
4
<class 'numpy.ndarray'>
5
<class 'numpy.ndarray'>
6
<class 'numpy.ndarray'>


In [1]:
#CONCATENATION
import numpy as np
n1=np.array([5,10,15,20])
n2=np.array([25,30,35,40])
print("Iteration")
for a in n1:
    print(a)
print("Iteration")
for a in n2:
    print(a)
Concate=np.concatenate((n1,n2))
print(Concate)
    

Iteration
5
10
15
20
Iteration
25
30
35
40
[ 5 10 15 20 25 30 35 40]


In [3]:
n1=np.array([5,10,15,20])
n2=np.array([25,30,35,40])
print("Iteration")
for a in n1:
    print(a)
print("Iteration")
for a in n2:
    print(a)
Concate1=np.stack((n1,n2))
Concate2=np.vstack((n1,n2))
Concate3=np.hstack((n1,n2))
Concate4=np.dstack((n1,n2))
Concate4=np.column_stack((n1,n2))
print(Concate1)
print(Concate2)
print(Concate3)
print(Concate4)


Iteration
5
10
15
20
Iteration
25
30
35
40
[[ 5 10 15 20]
 [25 30 35 40]]
[[ 5 10 15 20]
 [25 30 35 40]]
[ 5 10 15 20 25 30 35 40]
[[[ 5 25]
  [10 30]
  [15 35]
  [20 40]]]


In [9]:
#SPLITTING OF 1D ARRAY
n1=np.array([5,10,15,20])
arr=np.array_split(n1,2)
print("Array 1: ",arr[0])
print("Array 2: ",arr[1])

Array 1:  [ 5 10]
Array 2:  [15 20]


In [10]:
#SPLITTING OF 2D ARRAY
s=np.array([[23,50,60,90,100,20],
            [12,233,234,111,389,567]])
arr=np.array_split(s,2)
print("Array 1: ",arr[0])
print("Array 2: ",arr[1])

Array 1:  [[ 23  50  60  90 100  20]]
Array 2:  [[ 12 233 234 111 389 567]]


In [12]:
#SEARCHING FOR A VALUE IN NUMPY
n1=np.array([5,10,15,20])
print("Iteration")
for a in n1:
    print(a)
    output=np.where(n1==15)
    print(output)

Iteration
5
(array([2]),)
10
(array([2]),)
15
(array([2]),)
20
(array([2]),)


In [15]:
#SORTING
s=np.array([23,50,60,90,100,20])
T=np.sort(s)
print(T)
print(np.sort(s))


[ 20  23  50  60  90 100]
[ 20  23  50  60  90 100]


In [17]:
#SORTING IN STRING
s=np.array(['Kaira','Gullu','Zalak','Yogesh','Akansha','Vedant','Shreya'])
print('Sorted array : ',np.sort(s))

Sorted array :  ['Akansha' 'Gullu' 'Kaira' 'Shreya' 'Vedant' 'Yogesh' 'Zalak']


In [19]:
#TO FIND MINIMUM ELEMENTS IN HORIZONAL AND VERTICAL AXIS
s=np.array([[23,50,60,90],[100,20,12,233],[234,111,389,567]])
print("ITERATING 2D ARRAY....")
print("Iteration")
for a in s:
    print(a)
    print("MINIMUM VALUE....\n: ",s.min())
    print("MINIMUM VALUE IN VERTICAL AXIS....\n: ",s.min(axis=0))
    print("MINIMUM VALUE IN HORIZONTAL AXIS....\n: ",s.min(axis=1))

ITERATING 2D ARRAY....
Iteration
[23 50 60 90]
MINIMUM VALUE....
:  12
MINIMUM VALUE IN VERTICAL AXIS....
:  [23 20 12 90]
MINIMUM VALUE IN HORIZONTAL AXIS....
:  [ 23  12 111]
[100  20  12 233]
MINIMUM VALUE....
:  12
MINIMUM VALUE IN VERTICAL AXIS....
:  [23 20 12 90]
MINIMUM VALUE IN HORIZONTAL AXIS....
:  [ 23  12 111]
[234 111 389 567]
MINIMUM VALUE....
:  12
MINIMUM VALUE IN VERTICAL AXIS....
:  [23 20 12 90]
MINIMUM VALUE IN HORIZONTAL AXIS....
:  [ 23  12 111]


In [21]:
#INTERSECTION
n1=np.array([5,10,15,20,25])
n2=np.array([25,30,35,40,15])
print("Iteration")
for a in n1:
    print(a)
print("Iteration")
for a in n2:
    print(a)
    v=np.intersect1d(n1,n2)
    print(v)

Iteration
5
10
15
20
25
Iteration
25
[15 25]
30
[15 25]
35
[15 25]
40
[15 25]
15
[15 25]


In [24]:
n1=np.array([5,10,15,20,30,35])
n2=np.array([25,30,35,40,5,10])
print("Iteration")
for a in n1:
    print(a)
print("Iteration\n")
for a in n2:
    print(a)
    t=np.setdiff1d(n1,n2)
    print("The Uncommon elements : ",t)

Iteration
5
10
15
20
30
35
Iteration

25
The Uncommon elements :  [15 20]
30
The Uncommon elements :  [15 20]
35
The Uncommon elements :  [15 20]
40
The Uncommon elements :  [15 20]
5
The Uncommon elements :  [15 20]
10
The Uncommon elements :  [15 20]


In [26]:
#SET DIFFERENCE
n1=np.array([5,10,15,20])
n2=np.array([25,30,35,40])
t=np.setdiff1d(n1,n2)
print("The Uncommon elements : ",t)

The Uncommon elements :  [ 5 10 15 20]


In [27]:
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])

t = np.setdiff1d(n1, n2)
print(t)

[ 5 10]


In [29]:
#ARITHMECTIC OPERATIONS
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
s=np.sum([n1,n2])
print(s)
t=np.sum([n1,n2],axis=0)
print(t)
u=np.sum([n1,n2],axis=1)
print(u)


140
[20 30 40 50]
[50 90]


In [32]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
s=np.subtract(n1,n2)
print(s)


[-10 -10 -10 -10]


In [33]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
s=np.multiply(n1,n2)
print(s)

[ 75 200 375 600]


In [34]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
s=np.divide(n1,n2)
print(s)

[0.33333333 0.5        0.6        0.66666667]


In [35]:
#SCALAR OPERATIONS
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])

n1=n1+10
n2=n2+5
print(n1)
print(n2)

[15 20 25 30]
[20 25 30 35]


In [36]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])

n1=n1-10
n2=n2-5
print(n1)
print(n2)

[-5  0  5 10]
[10 15 20 25]


In [38]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])

n1=n1*10
n2=n2*5
print(n1)
print(n2)

[ 50 100 150 200]
[ 75 100 125 150]


In [39]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])

n1=n1/10
n2=n2/5
print(n1)
print(n2)

[0.5 1.  1.5 2. ]
[3. 4. 5. 6.]


In [40]:
#STATISTICAL OPERATIONS
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
n1=np.mean(n1)
print(n1)

12.5


In [41]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
n1=np.mean(n1)
n2=np.mean(n2)
print(n1)
print(n2)

12.5
22.5


In [42]:
n1 = np.array([5,10,15,20])
n2 = np.array([15,20,25,30])
n1=np.std(n1)
n2=np.std(n2)
print(n1)
print(n2)

5.5901699437494745
5.5901699437494745


In [1]:
#RANDOM MODULE IN NUMPY
from numpy import random

In [2]:
n=random.randint(5)
print("Random number= ",n)

Random number=  2


In [3]:
n=random.randint(5)
print("Random number= ",n)

Random number=  2


In [4]:
#with fixed size
n=random.randint(15,size=(4))
print("Random number= ",n)

Random number=  [2 5 0 2]


In [5]:
#By using choice method
n=random.choice([1,2,3,4,5])
print("Random number= ",n)

Random number=  5


In [6]:
n=random.choice(['stone','Paper','Scissor'])
print("Random number= ",n)

Random number=  Paper


In [8]:
#NUMPY Logs
import numpy as np
a=np.array((1,2,3))
print(a)
print(np.log2(a))

[1 2 3]
[0.        1.        1.5849625]


In [9]:
a=np.array((1,2,3))
print(a)
print(np.log10(a))

[1 2 3]
[0.         0.30103    0.47712125]


In [10]:
#NUMPY-LCM & HCF
import numpy as np
a=3
b=12
c=np.lcm(a,b)
print(c)


12


In [11]:
a=3
b=12
c=np.gcd(a,b)
print(c)

3
